### PR TITLE
Upgrading to Android V2 embedding

### LINKED ISSUE #7: Upgrade to Android V2 embedding to not rely on deprecated API
V2 is out there for a good while now and the time is ticking: Android Studio presents a warning

> The plugins `bluetooth_enable, share_files_and_screenshot_widgets` use a deprecated version of the Android embedding.
> To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
> If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

### PR DESCRIPTION
**Pull request by Alystrasz**
Upgrading both library and example app to use latest Flutter APIs.
The idea is to fix #7.

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
Thanks so much. I read through https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration but got stuck when `BluetoothEnablePlugin` needed to implement `FlutterPlugin` and `ActivityAware` because Android Studio IDE cannot import majoirty of the flutter specific package imports and I didn't have enough experience to do this blind.

**Comment by Alystrasz** [comment]
Yeah, this is the first time I migrate a plugin to V2, so I encountered same problems :smile: 
I tried to open the `android` folder as an Android project with Studio, but even with this, the IDE struggled to correctly import Flutter packages; I succeeded only thanks to the javadoc...

https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html
https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html

**Comment by MrCsabaToth** [comment]
I'm trying to convert https://pub.dev/packages/share_files_and_screenshot_widgets now. I figured that one way is to right click the android folder in the project tree in Android Studio and it has a menu to open up the Android part of the project only. That kicks off a gradle build. Than the gradelw files are missing for the plugin and the example as well. That can be generated by `gradle wrapper` command, however in my case I had extra difficulty that my Linux (Devuan) had a too old gradle. Interesting journey. I'm learning from your code now.

**Comment by MrCsabaToth** [comment]
@huitingyeong ?

**Comment by MrCsabaToth** [comment]
Hey @Alystrasz what's the reason for the close? I'm directly depending on your fork in my yaml, so if you plan to take it down I
ll fork it.

**Comment by Alystrasz** [comment]
Hello @MrCsabaToth, I cannot wait anymore for the author to accept the PR, so I decided to publish my own fork on the store: https://pub.dev/packages/bluetooth_enable_fork

If you need this feature in particular, I saved the repo state on this branch: https://github.com/Alystrasz/bluetooth_enable_fork/tree/chore/android-v2-embedding

**Pull request closed without merging**
